# Generated by Django 3.2.7 on 2021-09-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='black_list',
            field=models.BooleanField(default=False, verbose_name='ブラックユーザー'),
        ),
    ]
