# Generated by Django 3.2.7 on 2021-09-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_black_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop_owner',
            field=models.BooleanField(default=False, verbose_name='広告主'),
        ),
    ]
