# Generated by Django 3.2.7 on 2021-09-19 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_history',
            field=models.ManyToManyField(related_name='video_history', through='tube.History', to=settings.AUTH_USER_MODEL, verbose_name='視聴履歴'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_mylist',
            field=models.ManyToManyField(related_name='video_mylist', through='tube.MyList', to=settings.AUTH_USER_MODEL, verbose_name='マイリスト'),
        ),
    ]
